Dairy/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('',include("main.urls")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path,include
from . import views



urlpatterns = [
    path("",views.MainView.as_view(),name="menu"),
    path("add/",views.AddSchedule.as_view(),name="add"),
    path("delete/<int:schedule_id>/",views.DellView.as_view(),name="delete"),
    path("notes/",views.AddNotes.as_view(),name="add_notes"),
    path("task/",views.AddTask.as_view(),name="task"),
    path("notes/dell/<int:note_id>/",views.DellNotes.as_view(),name="del_notes"),
    path("task/dell/<int:task_id>/",views.DellTask.as_view(),name="dell_task"),
    path("accounts/",include("django.contrib.auth.urls")),
    path("profile/",views.ProfileView.as_view(),name="profile"),
    path("register/",views.Register.as_view(),name="register"),
    path("login/",views.LoginView.as_view(),name="login_view"),
    path("update_profile/",views.update_profile,name="update_profile")
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    email_address = models.EmailField(unique=True,max_length=50)
    USERNAME_FIELD = "email_address"
    username = models.CharField(max_length=100,blank=True,null=True)
    REQUIRED_FIELDS = ["username"]
    
    def __str__(self):
        return self.email_address

class Subject(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Schedule(models.Model):
    DAYS_OF_WEEK = [
        ("MON","Понедельник"),
        ("TUE","Вторник"),
        ("WED","Среда"),
        ("THU","Четверг"),
        ("FRI","Пятница"),
        ("SAT","Суббота"),
        ("SUN","Воскресенье")
    ]
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE) #* Привязываем к пользователю
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,related_name="schedule")
    classroom = models.CharField(verbose_name="Комната")
    day_of_week = models.CharField(max_length=3,choices=DAYS_OF_WEEK,verbose_name="День недели")
    time = models.CharField(verbose_name="Начало занятии")
    
    def __str__(self):
        return f"{self.subject} ({self.day_of_week} - {self.time})"
    

class Note(models.Model):
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    content = models.CharField()
    pub_date = models.DateTimeField()
    tag = models.ForeignKey(Tag,on_delete=models.CASCADE)


class Task(models.Model):
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    task = models.CharField()
    deadline = models.CharField()
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,related_name="tasks")


class Profile(models.Model):
    phone = models.CharField(max_length=50)
    user = models.OneToOneField(MyUser,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)

main/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Schedule,Note,Task,Profile
from .form import FeedbackModel,NoteForm,TaskForm,SignUpForm,UserForm,ProfileForm
from django.utils import timezone
from django.contrib.auth import login,authenticate
from django.views.generic import TemplateView,View
from django.contrib.auth.mixins import LoginRequiredMixin


class Login_Required(LoginRequiredMixin):
    login_url = "/login"
    redirect_field_name = "/"

class MainView(Login_Required,TemplateView):
    template_name = "main/index.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["context"] = Schedule.objects.filter(user=self.request.user)
        return context
    
class AddSchedule(Login_Required,View):
    form_class = FeedbackModel
    template_name = "main/add.html"

    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(user=self.request.user)
            return redirect("/")
        return render(request,self.template_name,{"form":form})
    
    def get(self,request,*args,**kwargs):
        form = self.form_class
        return render(request,self.template_name,{"form":form})
    
class DellView(View):
    def post(self,request,schedule_id,*args,**kwargs):
            schedule = get_object_or_404(Schedule,pk=schedule_id)
            schedule.delete()
            return redirect("/")
    



class AddNotes(Login_Required,TemplateView):
    template_name = "main/notes.html"

    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["information"] = Note.objects.filter(user=self.request.user)
        return context        

    def get(self,request):
        form = NoteForm()
        return render(request,self.template_name,{"note":form,**self.get_context_data()})    


    def post(self,request,):
        form = NoteForm(request.POST)
        if form.is_valid():
            notes = form.save(commit=False,user=request.user)
            notes.pub_date = timezone.now()
            notes.save()
            return redirect("/notes")
        return render(request,self.template_name,{"note":form,**self.get_context_data()})
    

class DellNotes(View):
    def post(self,request,note_id,*args,**kwargs):
        note = get_object_or_404(Note,pk=note_id)
        note.delete()
        return redirect("/notes")
    

class AddTask(Login_Required,TemplateView):
    template_name = "main/tasks.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["information"] = Task.objects.filter(user=self.request.user)
        return context
    
    def post(self,request,*args):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save(user=request.user)
            return redirect("/task")
        return render(request,self.template_name,{"form":form,**self.get_context_data()})
    
    def get(self,request,*args):
        form = TaskForm()
        return render(request,self.template_name,{"form":form,**self.get_context_data()})
    

class DellTask(View):
    def post(self,request,task_id):
        tasks = get_object_or_404(Task,pk=task_id)
        tasks.delete()
        return redirect("/task")




class Register(View):
    form_class = SignUpForm
    template_name = "main/register.html"
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect("/update_profile")
        return render(request,self.template_name,{"form":form})
    def get(self,request,*args,**kwargs):
        form = self.form_class()
        return render(request,self.template_name,{"form":form})

class LoginView(View):
    template_name = "main/login.html"
    def post(self,request,*args):
        form = UserForm(data=request.POST or None)
        if form.is_valid():
            email_address = form.cleaned_data.get("email_address")
            password = form.cleaned_data.get("password")
            user = authenticate(email_address=email_address,password=password)
            if user is not None:
                login(request,user)
                return redirect("/")
            
        return render(request,self.template_name,{"form":form})

    def get(self,request,*args):
        form = UserForm()
        return render(request,self.template_name,{"form":form})
    

class ProfileView(TemplateView):
    model = Profile
    template_name = "main/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['information'] = Profile.objects.get_or_create(user=self.request.user)
        return context


def update_profile(request):
    if request.user.is_authenticated:
        current_user,created = Profile.objects.get_or_create(user=request.user)
        form = ProfileForm(request.POST or None,instance=current_user)
        if form.is_valid():
            form.save()
            return redirect("/profile")
    
        return render(request,"main/update_profile.html",{"form":form})
    else:
        return redirect("/login")
        

main/templates/main/add.html
{% extends 'main/base.html' %}

{%block content %}

<div class="form-div">
    <form method="post" action="{% url  'add' %}" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Подтвердить</button>
    </form>
    
</div>

{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/notes.css' %}">
    <script src="{% static 'main/filter.js' %}" defer></script>
</head>
<body>
    <header>
        <ul>
            <li><a href="/">Расписание</a></li>
            <li>
                <a href="/add">Добавить расписание</a>
            </li>
            <li>
                <a href="/notes">Заметки</a>
            </li>
            <li>
                <a href="/task">Задачи</a>
            </li>

            {% if user.is_authenticated %}
                <li>
                    <div class="user-info">
                        <a href="{% url 'profile'%}"><div class="user-info-avatar" id="avatar"></div></a>
                        <div class="user-info-name" id="name">{{user.get_username}}</div>
                    </div>
                </li>


                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="leave">Выйти</button>
                    </form>
                </li>
            {% else %}
            <li>
                <a href="/login">Авторизация</a>
            </li>
            {%endif%}
        </ul>
    </header>
    {% block content %}
    {%endblock%}
</body>
</html>

main/templates/main/create_profile.html
{% extends "main/base.html" %}
{% block content %}
    {% if request.user.is_authenticated %}
    <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Подтвердить</button>
        </form>
    </div>
    {% else %}
    <a href="{% url 'login' %}">Войти</a>
    {% endif%}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}


<div class="schedule">
    <table>
        <thead>
            <tr>
                <th>Время</th>
                <th>День недели</th>
                <th>Предмет</th>
                <th>Комната</th>
                <th>Удалить</th>
            </tr>
        </thead>
        <tbody>
            {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Понедельник" %}
            <tr class="понедельник">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}

            <tr>
                {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Вторник" %}
            <tr class="вторник">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}

            <tr>
                {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Среда" %}
            <tr class="среда">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}

            <tr>
                {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Четверг" %}
            <tr class="четверг">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}

            <tr class="пятница">
                {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Пятница" %}
            <tr class="пятница">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}
            
            <tr class="суббота">
                {% for schedule in context %}
            {% if schedule.get_day_of_week_display == "Суббота" %}
            <tr class="суббота">
                <td>{{schedule.time}}</td>
                <td>{{schedule.get_day_of_week_display}}</td>
                <td>{{schedule.subject}}</td>
                <td>{{schedule.classroom}}</td>
                <td>
                    <form method="post" action="{% url 'delete' schedule.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete-btn"></button>
                    </form>
                </td>
            </tr>
            </tr>
            {%else%}
            <p></p>
            {%endif%}
            {%endfor%}
        </tbody>
    </table>
</div>    
{%endblock%}

main/templates/main/login.html
{% extends "main/base.html" %}
{% block content %}


{% if user.is_authenticated %}
      <p style="color: red; text-align:center">У вас недостаточно прав</p>  
  {% endif %}


<div class="form-div">
    <form method="post" action="{% url 'login_view' %}" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Подтвердить</button>
    </form>
</div>
<p class="register-p"><a href="/register">Создать аккаунт</a></p>

{% endblock %}

main/templates/main/notes.html
{% extends 'main/base.html' %}
{%block content %}

    <div class="form-div">
        <form method="post" action="{% url 'add_notes' %}" class="form">
            {% csrf_token %}
            {{ note.as_p }}
            <div>
                <button type="submit">Добавить</button>    
            </div>
        </form>
    </div>
    

<div class="search-field">
    <input type="search" placeholder="Поиск по тэгу" class="search-input">
</div>


<div class="grids">
    {% for info in information %}
        <div class="grid">
            <p>Время: {{info.pub_date}}</p>
            <span >Заметка: {{info.content }}</span>
            <p class="search-span">Тэг: {{info.tag}}</p>

            <form method="post" action="{% url 'del_notes' info.id %}">
                {% csrf_token %}
                <button class="delete-btn"></button>
            </form>
        </div>
    {% endfor %}
</div>    
{%endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}
{% block content %}

<h1 style="text-align: center;">Profile</h1>
<div class="card-body">
    <div class="border">
        <p>Имя: <span>{{information.name}}</span></p> <br>
        <p>Почта: <span>{{information.email}}</span></p> <br>
        <p>Номер: <span>{{information.phone}}</span></p> <br>
        <p>Город: <span>{{information.city}}</span></p> <br>
        <p>Страна: <span>{{information.country}}</span></p> <br>
        <a href="/update_profile">Редактировать</a>
    </div>
</div>
{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}
{% block content %}

    <div class="form-div">
        <form method="post" action="{% url 'register' %}" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Подтвердить</button>
        </form>
    </div>
{% endblock %}

main/templates/main/tasks.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="form-div">
        <form method="post" class="form">
            {% csrf_token %}
            {{form.as_p}}
            <div>
                <button>Добавить</button>
            </div>
        </form>
    </div>

    <div class="search-field">
        <input type="search" class="search-task" placeholder="Поиск">
    </div>

    <div class="grids" id="grids">
        {% for info in information %}
        <div class="grid" id="grid">
            <p class="subject-search">Предмет: {{info.subject }}</p>
            <span>Задача: {{info.task }}</span>
            <p>Срок: {{info.deadline }}</p>

            <form method="post" action="{% url 'dell_task' info.id %}">
                {% csrf_token %}
                <button class="delete-btn"></button>
            </form>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}

main/templates/main/update_profile.html
{% extends  "main/base.html" %}
{% block content %}
<div class="warning">
    <p>Вам не обязательно это все заполнять</p>
    <div>
        <span>Редактировать Профиль</span>
    </div>
</div>


<div class="form-div">
    <form method="post" action="{% url 'update_profile' %}" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подтвердить</button>
    </form>
</div>


{% endblock %}